# Indexing

Based off: https://numpy.org/doc/1.21/reference/arrays.indexing.html

In [2]:
import numpy as np

In [4]:
# basic slicing occurs with a slice object (constructed by start:stop:step), an int, or tuple of slice objects and integers
# all arrays generated by basic slicing return a view (not an actual distinct copy of that section of the array, just temporary)

# i:j:k
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[1:7:2])

[1 3 5]


In [10]:
# negative i and j correspond to n + i, n + j, where n is the number of elements in the array
# negative k corresponds to going backward

print(x[-2:10])
# starts at 10 - 2 = 8 and ends at index 9, inclusive

print(x[-3:3:-1])
# starts at index 10 - 3 = 7 and goes backward to index 4, inclusive

[8 9]
[7 6 5 4]


In [12]:
# if i is not given, it defaults to 0 for k > 0 and n - 1 for k < 0
# if j is not given, it defaults to n for k > 0 and -n - 1 for k < 0

print(x[5:])
# starts at index 5, ends at index n - 1, inclusive

[5 6 7 8 9]
